version: '3.2'
services:
# For prod!
  front:
    build: ../front
    container_name: "videosite-front"
    depends_on:
      - backend
    ports:
      - 8080:8080
    environment:
      - API_URL=localhost:3002

  backend:
    build: ../backend
    container_name: "videosite-backend"
    depends_on: 
      - mongo
      - mongo-express
    ports:
      - 3002:3002
    environment:
      HOST: 0.0.0.0
      - MONGODB_URI: mongodb://mongo/
      #- SET_CONTAINER_TIMEZONE=true
      #- CONTAINER_TIMEZONE=Europe/Helsinki

  mongo:
      image: mongo
      restart: always
      ports:
        - 27017:27017
      # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
        #MONGO_INITDB_ROOT_PASSWORD: 123

 mongo-express:
     image: mongo-express
     restart: always
     ports:
       - 8081:8081
    # environment:
      #  ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #  ME_CONFIG_MONGODB_ADMINPASSWORD: 123